[package]
name = "storage_bucket"
version = "0.1.0"
authors = ["Maix0 <maix522@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[features]
default = ["zip"]

[dependencies]
zip = {version="0.5.11", optional=true}
